<a href="https://colab.research.google.com/github/ishaak15/UNSW-IDS-Feature-Selection/blob/main/Copy_of_Training_and_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import matplotlib
import matplotlib.pyplot as plt
import os
import math
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_validate
from sklearn import datasets, preprocessing, feature_extraction, neighbors
from sklearn import linear_model, svm, metrics, ensemble, tree, ensemble
from sklearn.model_selection import train_test_split
from copy import copy
import urllib
import csv

import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import plotly.graph_objs as go

from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 


from sklearn.naive_bayes import GaussianNB
from yellowbrick.classifier import ClassificationReport

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC # "Support Vector Classifier" 
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from zipfile import ZipFile
import collections

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning:

The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.



In [2]:
!git clone https://github.com/ishaak15/UNSW-IDS-Feature-Selection.git

Cloning into 'UNSW-IDS-Feature-Selection'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 52 (delta 1), reused 0 (delta 0), pack-reused 37
Unpacking objects: 100% (52/52), done.


In [3]:
cd UNSW-IDS-Feature-Selection/

/content/UNSW-IDS-Feature-Selection


In [4]:
ls

bayes_10.sav   clfKNN20.sav                        README.md
bayes_20.sav   clfKNN_all.sav                      Testset1.csv
bayes_all.sav  Copy_of_Training_and_Testing.ipynb  Testset2.csv
clfDT_10.sav   Dataset1.csv                        Testset3.csv
clfDT_20.sav   Dataset2.csv                        Training_and_Testing.ipynb
clfDT_all.sav  Dataset3.csv                        UNSW_IDS_analysis.ipynb
clfKNN10.sav   LICENSE                             UNSW_NB15_testing-set.csv


In [5]:
df1 = pd.read_csv('Dataset1.csv',index_col=0)
df2 = pd.read_csv('Dataset2.csv',index_col=0)
df3 = pd.read_csv('Dataset3.csv',index_col=0)

In [6]:
tf1 = pd.read_csv('Testset1.csv',index_col=0)
tf2 = pd.read_csv('Testset2.csv',index_col=0)
tf3 = pd.read_csv('Testset3.csv',index_col=0)

In [7]:
df1_xtrain=df1.iloc[: , :-1]
df1_ytrain=df1.iloc[:,-1]
df2_xtrain=df2.iloc[: , :-1]
df2_ytrain=df2.iloc[:,-1]
df3_xtrain=df3.iloc[: , :-1]
df3_ytrain=df3.iloc[:,-1]

In [8]:
df1_xtest=tf1.iloc[: , :-1]
df1_ytest=tf1.iloc[:,-1]
df2_xtest=tf2.iloc[: , :-1]
df2_ytest=tf2.iloc[:,-1]
df3_xtest=tf3.iloc[: , :-1]
df3_ytest=tf3.iloc[:,-1]

In [ ]:
#KNN

In [ ]:
clfKNN10=neighbors.KNeighborsClassifier()
clfKNN10.fit(df1_xtrain,df1_ytrain)
#clfKNN10.fit(df1_xtrain,df1_ytrain)

print ("\t\tKNN Classification of UNSW-NB15\n\n\t\tTop 10 Features ")

yt_pred_10 = clfKNN10.predict(df1_xtest)
results = confusion_matrix(df1_ytest, yt_pred_10) 
print ('Confusion Matrix :')
print(results) 


accKNN10=accuracy_score(df1_ytest,yt_pred_10)
print("Accuracy: ",accKNN10)
preKNN10=precision_score(df1_ytest, yt_pred_10, average='macro')
print("Precision Score: ",preKNN10)
f1KNN10=f1_score(df1_ytest, yt_pred_10, average='macro')
print("F1 Score: ",f1KNN10)
reKNN10=recall_score(df1_ytest, yt_pred_10, average='macro')  
print("Recall: ",reKNN10)


		KNN Classification of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[  208   131    42    58   129    16    32    61     0     0]
 [  198   121    13    49   134    18    16    33     1     0]
 [  822   758   472   913   502    21   202   372    27     0]
 [  955   835   503  6664   944    39   616   540    33     3]
 [  444   315    97   469  3357    54  1111   164    50     1]
 [   17    11    34   375   168 18078   140    44     4     0]
 [  496    52   218  1986  7076    20 26822   233    93     4]
 [   82   102    51   324   117     5    71  2737     5     2]
 [    5     7    12    50   161     6    51    32    54     0]
 [    0     1     2    26    11     0     3     0     0     1]]
Accuracy:  0.7107078657144246
Precision Score:  0.41756373950870634
F1 Score:  0.4023931552335053
Recall:  0.44140047486900985


In [ ]:
clfKNN20=neighbors.KNeighborsClassifier()
clfKNN20.fit(df2_xtrain,df2_ytrain)

print ("\t\tKNN Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

y_pred_20 = clfKNN20.predict(df2_xtest)
results = confusion_matrix(df2_ytest, y_pred_20) 
print ('Confusion Matrix :')
print(results) 


accKNN20=accuracy_score(df2_ytest,y_pred_20)
print("Accuracy: ",accKNN20)
preKNN20=precision_score(df2_ytest, y_pred_20, average='macro')
print("Precision Score: ",preKNN20)
f1KNN20=f1_score(df2_ytest, y_pred_20, average='macro')
print("F1 Score: ",f1KNN20)
reKNN20=recall_score(df2_ytest, y_pred_20, average='macro')  
print("Recall: ",reKNN20)


		KNN Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  267   167    15    69   117    16    17     9     0     0]
 [  251   109     6    65   118    18    11     5     0     0]
 [ 1150  1136   184   646   494    22   307   129    21     0]
 [ 1321  1139   396  4316  1854    39  1749   290    28     0]
 [  599   332   140  2053  1702    56  1023   122    35     0]
 [   30    22    26   304   220 18083   132    51     3     0]
 [  132    71   537  7955  4981    21 22760   473    69     1]
 [  126   152    91   985   400     7   405  1325     5     0]
 [    7     6    13   109   126     5    52    17    43     0]
 [    0     0     1    22     8     0    13     0     0     0]]
Accuracy:  0.5925885439440315
Precision Score:  0.3273066113090913
F1 Score:  0.3053129978339978
Recall:  0.336096541715301


In [ ]:
clfKNN20=neighbors.KNeighborsClassifier()
clfKNN20.fit(df3_xtrain,df3_ytrain)

print ("\t\tKNN Analysis of UNSW-NB15\n\n\t\tAll Features ")

y_pred_all = clfKNN20.predict(df3_xtest)
results = confusion_matrix(df3_ytest, y_pred_all) 
print ('Confusion Matrix :')
print(results) 


accKNNall=accuracy_score(df3_ytest, y_pred_all)
print("Accuracy: ",accKNNall)
preKNNall=precision_score(df3_ytest, y_pred_all, average='macro')
print("Precision Score: ",preKNNall)
f1KNNall=f1_score(df3_ytest, y_pred_all, average='macro')
print("F1 Score: ",f1KNNall)
reKNNall=recall_score(df3_ytest, y_pred_all, average='macro')  
print("Recall: ",reKNNall)


		KNN Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[  336   161     1    44   101    16    17     1     0     0]
 [  304    98     1    44   105    18    11     2     0     0]
 [ 1491  1070   101   581   437    22   305    61    21     0]
 [ 1671  1073   319  4245  1794    39  1743   220    28     0]
 [  726   307   123  2007  1672    56  1024   112    35     0]
 [   37    21    26   301   219 18083   130    51     3     0]
 [  115    55   537  7955  5009    21 22765   473    69     1]
 [  164   146    81   981   392     7   405  1315     5     0]
 [    6     3    13   109   132     5    50    16    44     0]
 [    0     0     1    22     8     0    13     0     0     0]]
Accuracy:  0.5910095710051985
Precision Score:  0.3265665197965294
F1 Score:  0.3034833731074776
Recall:  0.34123127222810123


In [ ]:
#Decision TREE

In [ ]:
clfDT_10 = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

# Train Decision Tree Classifer
clfDT_10 = clfDT_10.fit(df1_xtrain,df1_ytrain)

#Predict the response for test dataset
y_pred_DT10 = clfDT_10.predict(df1_xtest)


#print ("\t\tMajor Verifcation")
results_DT10 = confusion_matrix(df1_ytest, y_pred_DT10) 
print ('Confusion Matrix :')
print(results_DT10) 


print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_DT10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_DT10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_DT10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_DT10, average='macro'))



		Decision Tree Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[  376    82     0     3   186     0    28     2     0     0]
 [  321    53     3    11   187     0     4     0     4     0]
 [ 1490  1023   514   529   377    33    60    24    36     3]
 [ 1715   960   592  6511   633   116   231   227   127    20]
 [  724   144   129   511  2963    40  1276     4   267     4]
 [   20    25    61   223    55 18443    20     2    17     5]
 [  609     8  1064  1171  7281   122 26574    30   140     1]
 [  158   150    39   266    39     5    40  2758    39     2]
 [    1     7    14    41    29     4    14     3   265     0]
 [    0     1     0    11     0     1     1     0     1    29]]
Accuracy Score : 0.7103677792352913
Precision Score:  0.4834595761528261
F1 Score:  0.4877509998431407
Recall:  0.5690263240723327


In [ ]:
clfDT_20 = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

# Train Decision Tree Classifer
clfDT_20 = clfDT_20.fit(df2_xtrain,df2_ytrain)

#Predict the response for test dataset
y_pred_DT20 = clfDT_20.predict(df2_xtest)


#print ("\t\tMajor Verifcation")
results_DT20 = confusion_matrix(df2_ytest, y_pred_DT20) 
print ('Confusion Matrix :')
print(results_DT20)

print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_DT20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_DT20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_DT20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_DT20, average='macro'))

		Decision Tree Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  506   110     1    38     1     3    14     1     3     0]
 [  493    50     6    10     8     2    10     0     4     0]
 [ 1736  1029   542   519    89    44    68    26    36     0]
 [ 2083   962   651  6467   166    95   299   303    98     8]
 [ 1071   144    89   374  2682    29  1494    18   161     0]
 [   26    26    53   213    41 18465    18     8    16     5]
 [  675    10  1268  1491  7414    72 25889    41   139     1]
 [  163   140    37   275    35     3    35  2762    45     1]
 [    2     7    15    46    29     3    15     4   257     0]
 [    0     1     2    13     0     1     0     1     1    25]]
Accuracy Score : 0.70015303891561
Precision Score:  0.4991935628488952
F1 Score:  0.4939799886246779
Recall:  0.5705405158286443


In [ ]:
clfDT_all = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tAll Features ")

# Train Decision Tree Classifer
clfDT_all = clfDT_all.fit(df3_xtrain,df3_ytrain)

#Predict the response for test dataset
y_pred_DTall = clfDT_all.predict(df3_xtest)

#print ("\t\tMajor Verifcation")
results_DTall = confusion_matrix(df3_ytest, y_pred_DTall) 
print ('Confusion Matrix :')
print(results_DTall)

print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_DTall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_DTall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_DTall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_DTall, average='macro'))

		Decision Tree Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[  502   115     0    53     0     1     5     0     1     0]
 [  495    61     1     8     4     1     9     0     4     0]
 [ 1717  1117   538   506    56    31    63    25    36     0]
 [ 2087  1040   557  6538   165    96   333   221    86     9]
 [ 1057   184    79   354  2703    28  1507     4   146     0]
 [   26    19    66   245    32 18438    21     3    16     5]
 [  701     9  1067  1435  7459   249 25907    43   129     1]
 [  166   161    40   298    14     6    29  2737    44     1]
 [    0     6    13    50    35     3    15     4   252     0]
 [    0     0     4    13     1     1     0     2     0    23]]
Accuracy Score : 0.7008089199825098
Precision Score:  0.5020915741277562
F1 Score:  0.4929098967670565
Recall:  0.5660451272876671


In [ ]:
#Gaussian Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB

In [ ]:
print(df1_ytrain.unique())

[6 1 0 4 8 7 3 2 9 5]


In [ ]:
bayes_10 = MultinomialNB()
#bayes_10.partial_fit(df1_xtrain,df1_ytrain,df1_ytrain.unique())
bayes_10.fit(df1_xtrain,df1_ytrain)

print ("\t\tGaussain Naive Bayes Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")
y_pred_gnb10 = bayes_10.predict(df1_xtest)

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df1_ytest, y_pred_gnb10) 
print ('Confusion Matrix :')
print(results) 

print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_gnb10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_gnb10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_gnb10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_gnb10, average='macro'))


		Gaussain Naive Bayes Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[  601     0     0    14     0     1    61     0     0     0]
 [  483     0     0    38     1     2    59     0     0     0]
 [ 2473     0     0   510    72    78   934    10    12     0]
 [ 2697     0     0  1738   125    56  6494     2    20     0]
 [ 1222     0     0   752   550   374  3111     7    46     0]
 [   28     0     0   109    95 18159   475     1     4     0]
 [  193     0     1  4062  1501  2792 28284    18   149     0]
 [ 1541     0     0    68     8    15  1858     6     0     0]
 [   75     0     0     1    36     9   192     6    59     0]
 [    0     0     0     2     4     2    36     0     0     0]]
Accuracy Score : 0.5999732789194967
Precision Score:  0.23827456767032631
F1 Score:  0.2239561902839405
Recall:  0.30190991296773395


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
bayes_20 = MultinomialNB()
bayes_20.fit(df2_xtrain,df2_ytrain)

print ("\t\tGaussian Naive Bayes Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

y_pred_gnb20 = bayes_20.predict(df2_xtest)

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df2_ytest, y_pred_gnb20) 
print ('Confusion Matrix :')
print(results)

print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_gnb20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_gnb20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_gnb20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_gnb20, average='macro'))

		Gaussian Naive Bayes Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[    3     0     2    40     0   614     0     0     0    18]
 [    3     0    10    36     0   515     4     0     0    15]
 [   31     0    87   677     0  2903    17     0     0   374]
 [   36     0   128  5200     0  3163    76     0     0  2529]
 [   45     0    54  2445     0  2250     0     0     0  1268]
 [    4     0     4   345     0 18343     4     0     0   171]
 [  585     0    73 14651     0  5965  7847     1     1  7877]
 [    8     0    22  1262     0  1601     0     0     0   603]
 [    0     0     0   130     0   185     0     0     0    63]
 [    0     0     0    24     0     6     0     0     0    14]]
Accuracy Score : 0.3825244133508235
Precision Score:  0.1947161142507347
F1 Score:  0.135809387243145
Recall:  0.19951131812748615


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
bayes_all = MultinomialNB()
bayes_all.fit(df3_xtrain,df3_ytrain)

print ("\t\tGaussian Naive Bayes Analysis of UNSW-NB15\n\n\t\tAll Features ")
y_pred_gnball = bayes_all.predict(df3_xtest)

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df3_ytest, y_pred_gnball) 
print ('Confusion Matrix :')
print(results)

print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_gnball) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_gnball, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_gnball, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_gnball, average='macro'))

		Gaussian Naive Bayes Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[    3     0     2    40     0   614     0     0     0    18]
 [    3     0    10    36     0   515     4     0     0    15]
 [   31     0    87   677     0  2903    17     0     0   374]
 [   36     0   128  5200     0  3163    76     0     0  2529]
 [   45     0    54  2445     0  2250     0     0     0  1268]
 [    4     0     4   345     0 18343     4     0     0   171]
 [  615     0    14 14654     0  6027  7813     1     1  7875]
 [    8     0    22  1262     0  1601     0     0     0   603]
 [    0     0     0   130     0   185     0     0     0    63]
 [    0     0     0    24     0     6     0     0     0    14]]
Accuracy Score : 0.38211145119759027
Precision Score:  0.1988094523267321
F1 Score:  0.13564830638485165
Recall:  0.19941942623559425


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
#Random Forest Classifier 


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

#Create a Gaussian Classifier
clfRF_10=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_10.fit(df1_xtrain,df1_ytrain)

y_pred_RF10=clfRF_10.predict(df1_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

results_10 = confusion_matrix(df1_ytest, y_pred_RF10) 
print ('Confusion Matrix :')
print(results_10) 
print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_RF10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_RF10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_RF10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_RF10, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[   21   129    14    76   404     1    19    10     3     0]
 [   14    78     9    25   421     2    17     8     9     0]
 [  528  1244   508   859   784    19    31    71    44     1]
 [  495  1152   197  7591  1245    25   134   212    76     5]
 [   78   223    26   467  4006     7   987    22   245     1]
 [    7    11    43   401    60 18317     8     2    20     2]
 [  315     1    60   736  7402     5 28358     6   116     1]
 [   66   156    26   324    88     1    15  2787    33     0]
 [    0     1    11    51    34     0    10     2   268     1]
 [    0     0     0    20     1     1     1     0     0    21]]
Accuracy Score : 0.7525020648107662
Precision Score:  0.543903613379478
F1 Score:  0.5037619188990108
Recall:  0.5352331164849445


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

#Create a Gaussian Classifier
clfRF_20=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_20.fit(df2_xtrain,df2_ytrain)

y_pred_RF20=clfRF_20.predict(df2_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

results_20 = confusion_matrix(df2_ytest, y_pred_RF20) 
print ('Confusion Matrix :')
print(results_20) 
print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_RF20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_RF20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_RF20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_RF20, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  113   189    15    45   222     0    16    74     3     0]
 [  102   120    16    19   245     0     2    73     6     0]
 [  510  1496   501   765   563     7    17   186    44     0]
 [  586  1441   149  7565   842    14    89   373    70     3]
 [  250   334    35   371  3845     1   869   148   209     0]
 [    2    11    45   371    62 18346     5     6    20     3]
 [  411     1    33   766  7631     6 28026     6   119     1]
 [   53   185    21   315    70     0     9  2818    25     0]
 [    0     1    12    53    38     0     8     2   263     1]
 [    0     0     0    27     2     1     2     0     0    12]]
Accuracy Score : 0.7482995676043337
Precision Score:  0.5386815521343815
F1 Score:  0.48974037646502283
Recall:  0.5313317654818648


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 30 Features ")

#Create a Random Forest Classifier
clfRF_all=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_all.fit(df3_xtrain,df3_ytrain)

y_pred_RFall=clfRF_all.predict(df3_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

results_all = confusion_matrix(df3_ytest, y_pred_RFall) 
print ('Confusion Matrix :')
print(results_all) 
print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_RFall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_RFall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_RFall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_RFall, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 30 Features 
Confusion Matrix :
[[   56   254     6    61   242     0     3    52     3     0]
 [   56   169     7    23   265     0     0    56     7     0]
 [  320  1714   438   806   555     9     9   192    46     0]
 [  366  1696    96  7628   845    19    87   320    73     2]
 [  139   444    25   349  3917     2   856   113   217     0]
 [    0    10    42   396    61 18328     5     7    20     2]
 [  490     0    30   721  7639     7 27976     7   129     1]
 [   34   209    17   319    66     1     8  2813    29     0]
 [    0     0    11    55    37     0    11     2   262     0]
 [    0     0     0    33     3     1     0     0     0     7]]
Accuracy Score : 0.7481173784190837
Precision Score:  0.5419639266247861
F1 Score:  0.4739566821908319
Recall:  0.5195282874921998


In [ ]:
#Logistic Regression Classifier 


In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

logisticRegr_10 = LogisticRegression(C=1e5, solver='newton-cg',max_iter=1000, multi_class='multinomial')

logisticRegr_10.fit(df1_xtrain,df1_ytrain)

y_pred_LR10 = logisticRegr_10.predict(df1_xtest)

results_LR10 = confusion_matrix(df1_ytest, y_pred_LR10) 
print ('Confusion Matrix :')
print(results_LR10) 
print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_LR10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_LR10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_LR10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_LR10, average='macro'))

		Logistic Regression Analysis of UNSW-NB15

		Top 10 Features 


/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:466: LineSearchWarning:

The line search algorithm did not converge

/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:314: LineSearchWarning:

The line search algorithm did not converge

/usr/local/lib/python3.7/dist-packages/sklearn/utils/optimize.py:212: ConvergenceWarning:

newton-cg failed to converge. Increase the number of iterations.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



Confusion Matrix :
[[    0     0     0    67   603     1     4     2     0     0]
 [    0     0     0    30   534     2    10     7     0     0]
 [    0     0     0   701  3023    53   229    83     0     0]
 [    0     0     4  5355  4777    36   873    87     0     0]
 [    0     0     0   190  4906   347   574    45     0     0]
 [    0     0     0   244   520 17912   186     9     0     0]
 [    0     0     0  4280 10600  2693 19298   129     0     0]
 [    0     0     0   118  3345    19     6     8     0     0]
 [    0     0     0    17   343     6     0    12     0     0]
 [    0     0     0     0    33     2     9     0     0     0]]
Accuracy Score : 0.576677355098868
Precision Score:  0.24395420989882374
F1 Score:  0.2330576404871651
Recall:  0.2763386674857679


In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW NB15\n\n\t\tTop 20 Features ")

logisticRegr_20 = LogisticRegression(C=1e5, solver='newton-cg',max_iter=1000, multi_class='multinomial')

logisticRegr_20.fit(df2_xtrain,df2_ytrain)

y_pred_LR20 = logisticRegr_20.predict(df2_xtest)

results_LR20 = confusion_matrix(df2_ytest, y_pred_LR20) 
print ('Confusion Matrix :')
print(results_LR20) 
print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_LR20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_LR20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_LR20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_LR20, average='macro'))


		Logistic Regression Analysis of UNSW NB15

		Top 20 Features 


/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:466: LineSearchWarning:

The line search algorithm did not converge

/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:314: LineSearchWarning:

The line search algorithm did not converge

/usr/local/lib/python3.7/dist-packages/sklearn/utils/optimize.py:212: ConvergenceWarning:

newton-cg failed to converge. Increase the number of iterations.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



Confusion Matrix :
[[    0     0     0    24   618     2    33     0     0     0]
 [    0     0     0    21   527     5    30     0     0     0]
 [    0     0    12   465  2920   123   568     1     0     0]
 [    0     0     3  2640  4041   122  4323     3     0     0]
 [    0     0     0  1354  3715   379   614     0     0     0]
 [    0     0     1   177   224 18168   301     0     0     0]
 [    0     0     0  4308 10244  2806 19639     3     0     0]
 [    0     0     0   425  2851    45   175     0     0     0]
 [    0     0     0    72   234    33    39     0     0     0]
 [    0     0     0    12    19     2    11     0     0     0]]
Accuracy Score : 0.5365350046154593
Precision Score:  0.27752510329555236
F1 Score:  0.20200551358150495
Recall:  0.23464537572388955


In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW-NB15\n\n\t\tTop 30 Features ")

logisticRegr_all = LogisticRegression(C=1e5, solver='Newton-cg', multi_class='multinomial')

logisticRegr_all.fit(df3_xtrain,df3_ytrain)

y_pred_LRall = logisticRegr_all.predict(df3_xtest)

results_LRall = confusion_matrix(df3_ytest, y_pred_LRall) 
print ('Confusion Matrix :')
print(results_LRall) 
print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_LRall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_LRall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_LRall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_LRall, average='macro'))



In [53]:
X = df1_xtrain
Y = df1_ytrain
C = df3_ytest
T = df1_xtest
scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)

y_train1 = np.array(Y)
y_test1 = np.array(C)

y_train= to_categorical(y_train1)
y_test= to_categorical(y_test1)


# reshape input to be [samples, time steps, features]
X_train = np.reshape(trainX, (trainX.shape[0],trainX.shape[1],1))
X_test = np.reshape(testT, (testT.shape[0],testT.shape[1],1))


from keras.models import Sequential
from keras import layers

input_dim = df1_xtrain.shape[1]  # Number of features

model = Sequential()
model.add(layers.Dense(10, input_shape=(15, 1), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_49 (Dense)             (None, 15, 10)            20        
_________________________________________________________________
flatten_5 (Flatten)          (None, 150)               0         
_________________________________________________________________
dense_50 (Dense)             (None, 32)                4832      
_________________________________________________________________
dense_51 (Dense)             (None, 10)                330       
Total params: 5,182
Trainable params: 5,182
Non-trainable params: 0
_________________________________________________________________


In [54]:
history = model.fit(X_train, y_train,
                    epochs=100 #,
                    #verbose=False
                    )

Epoch 1/100
3367/3367 [==============================] - 5s 1ms/step - loss: 1.4368 - accuracy: 0.4885
Epoch 2/100
3367/3367 [==============================] - 4s 1ms/step - loss: 1.2129 - accuracy: 0.5175
Epoch 3/100
3367/3367 [==============================] - 4s 1ms/step - loss: 1.1274 - accuracy: 0.5543
Epoch 4/100
3367/3367 [==============================] - 4s 1ms/step - loss: 1.0683 - accuracy: 0.5859
Epoch 5/100
3367/3367 [==============================] - 4s 1ms/step - loss: 1.0266 - accuracy: 0.6133
Epoch 6/100
3367/3367 [==============================] - 4s 1ms/step - loss: 0.9900 - accuracy: 0.6360
Epoch 7/100
3367/3367 [==============================] - 4s 1ms/step - loss: 0.9693 - accuracy: 0.6464
Epoch 8/100
3367/3367 [==============================] - 4s 1ms/step - loss: 0.9479 - accuracy: 0.6547
Epoch 9/100
3367/3367 [==============================] - 5s 1ms/step - loss: 0.9444 - accuracy: 0.6531
Epoch 10/100
3367/3367 [==============================] - 5s 1ms/step - l

In [56]:
loss, accuracy = model.evaluate(X_train, y_train, verbose=True)
print("Training Accuracy: {:.4f}".format(accuracy))

#loss, accuracy = model.evaluate(y_test, X_test, verbose=True)
#print("Testing Accuracy:  {:.4f}".format(accuracy))

3367/3367 [==============================] - 4s 1ms/step - loss: 0.6887 - accuracy: 0.7500
Training Accuracy: 0.7500


In [21]:
#CNN 1D
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda
from keras.layers import Embedding
from keras.layers import Convolution1D,MaxPooling1D, Flatten
from keras.datasets import imdb
from keras import backend as K
#from sklearn.cross_validation import train_test_split
import pandas as pd
from keras.utils.np_utils import to_categorical

from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Convolution1D, Dense, Dropout, Flatten, MaxPooling1D
from keras.utils import np_utils
import numpy as np
import h5py
from keras import callbacks
from keras.layers import LSTM, GRU, SimpleRNN
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

In [22]:
X = df1_xtrain
Y = df1_ytrain
C = df3_ytest
T = df1_xtest



In [23]:
scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)

y_train1 = np.array(Y)
y_test1 = np.array(C)

y_train= to_categorical(y_train1)
y_test= to_categorical(y_test1)


# reshape input to be [samples, time steps, features]
X_train = np.reshape(trainX, (trainX.shape[0],trainX.shape[1],1))
X_test = np.reshape(testT, (testT.shape[0],testT.shape[1],1))


cnn = Sequential()
cnn.add(Convolution1D(64, 1, activation="relu",input_shape=(15, 1)))
#cnn.add(MaxPooling1D(pool_length=(2)))
cnn.add(Flatten())
cnn.add(Dense(128, activation="relu"))
cnn.add(Dropout(0.5))
cnn.add(Dense(10, activation="softmax"))

# define optimizer and objective, compile cnn

cnn.compile(loss="categorical_crossentropy", optimizer="adam",metrics=['accuracy'])

# train
checkpointer = callbacks.ModelCheckpoint(filepath="results/checkpoint-{epoch:02d}.hdf5", verbose=1, save_best_only=True, monitor='val_acc',mode='max')
csv_logger = CSVLogger('results/cnn1results/cnntrainanalysis1.csv',separator=',', append=False)
cnn.fit(X_train, y_train, batch_size=40 ,epochs=100)
#cnn.save("results/cnn1results/cnn_model.hdf5")
#,validation_data=(X_test, y_test),callbacks=[checkpointer,csv_logger]


Epoch 1/100
2694/2694 [==============================] - 10s 3ms/step - loss: 1.3554 - accuracy: 0.5005
Epoch 2/100
2694/2694 [==============================] - 10s 4ms/step - loss: 1.1883 - accuracy: 0.5390
Epoch 3/100
2694/2694 [==============================] - 10s 4ms/step - loss: 1.1328 - accuracy: 0.5607
Epoch 4/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0925 - accuracy: 0.5789
Epoch 5/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0749 - accuracy: 0.5902
Epoch 6/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0533 - accuracy: 0.6002
Epoch 7/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0547 - accuracy: 0.6000
Epoch 8/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0331 - accuracy: 0.6119
Epoch 9/100
2694/2694 [==============================] - 9s 3ms/step - loss: 1.0298 - accuracy: 0.6146
Epoch 10/100
2694/2694 [==============================] - 9s 3ms/step 

In [ ]:

scaler=Normalizer().fit(df1_xtrain)
x_train=scaler.transform(df1_xtrain)

scaler=Normalizer().fit(df1_xtest)
x_test=scaler.transform(df1_xtest)

x=np.expand_dims(x_train,axis=2)
y=np.expand_dims(x_test,axis=2)


tr_lb=df1_ytrain.to_numpy()
te_lb=df3_ytest.to_numpy()

cnn_1D=Sequential()
cnn_1D.add(Conv1D(64,1,activation='relu',input_shape=(10,1)))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(MaxPooling1D(3))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(GlobalAveragePooling1D())
cnn_1D.add(Dropout(0.5))
cnn_1D.add(Dense(6,activation='sigmoid'))
cnn_1D.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='rmsprop',
    metrics=(['accuracy'])
)
cnn_1D.fit(x,tr_lb,batch_size=80,epochs=30)
score=cnn_1D.evaluate(y,te_lb,batch_size=80)
print(score)



Epoch 1/30
1347/1347 [==============================] - 6s 4ms/step - loss: nan - accuracy: 0.0150
Epoch 2/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0150
Epoch 3/30
1347/1347 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.0146
Epoch 4/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0151
Epoch 5/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0143
Epoch 6/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0149
Epoch 7/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0151
Epoch 8/30
1347/1347 [==============================] - 5s 3ms/step - loss: nan - accuracy: 0.0150
Epoch 9/30
1347/1347 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.0154
Epoch 10/30
1347/1347 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.0148
Epoch 11/

In [ ]:
#Ada Boost with DT
from sklearn.ensemble import AdaBoostClassifier


In [ ]:
print ("\t\tAdaBoost using Decision Tree Analysis of UNSW NB15\n\n\t\tTop 10 Features ")



abc10 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=3), algorithm="SAMME", n_estimators=500)
abc10.fit(df1_xtrain, df1_ytrain)

#Predict the response for test dataset
y_pred_Ada10 = abc10.predict(df1_xtest)


results_Ada10 = confusion_matrix(df1_ytest, y_pred_Ada10) 
print ('Confusion Matrix :')
print(results_Ada10) 

print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_Ada10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_Ada10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_Ada10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_Ada10, average='macro'))


		AdaBoost using Decision Tree Analysis of UNSW NB15

		Top 10 Features 
Confusion Matrix :
[[  281     4    60    51   206     0    62    13     0     0]
 [  179     6    61    97   214     1     8    13     4     0]
 [ 1862   134   237   854   525    68   169   200    38     2]
 [ 1854   155   390  6189   859   253   868   517    44     3]
 [  539    12   134   370  1076     2  3825    66    36     2]
 [   12     2    53   804    41 17845    89    15    10     0]
 [  440    23   170   908  3039    18 32249    20   127     6]
 [  216    28    22   196    78     7    87  2842    20     0]
 [    0     0    25    50    44     0    45    15   199     0]
 [    0     1     0    31     4     3     1     0     2     2]]
Accuracy Score : 0.7400038867026186
Precision Score:  0.4257907888811636
F1 Score:  0.4122616517585579
Recall:  0.4418846498278154


In [ ]:
print ("\t\tAdaBoost using DT Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

abc20 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=3), algorithm="SAMME",n_estimators=500)
abc20.fit(df2_xtrain, df2_ytrain)

y_pred_Ada20 = abc20.predict(df2_xtest)



results_Ada10 = confusion_matrix(df2_ytest, y_pred_Ada20) 
print ('Confusion Matrix :')
print(results_Ada10) 

print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_Ada20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_Ada20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_Ada20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_Ada20, average='macro'))


		AdaBoost using DT Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  424    57     3    18    44     0    55    76     0     0]
 [  359    45    15    24    51    11     4    71     3     0]
 [ 1378   689   331   926   328    32   108   252    39     6]
 [ 1640   687  1031  6096   478   219   363   553    40    25]
 [  826   133    82   151  1658    11  2933   194    53    21]
 [   13     6   260   370    56 18055    91     7    12     1]
 [  658     6   307   637  5202    27 30030    14   101    18]
 [  133   110    59   241    86     7    34  2820     5     1]
 [    0     2    36    54    45     0    36    12   193     0]
 [    0     0     5    31     2     2     2     0     0     2]]
Accuracy Score : 0.7245542437934217
Precision Score:  0.4221556965595627
F1 Score:  0.42149595164438824
Recall:  0.4736599285185821


In [ ]:
print ("\t\tAdaBoost using DT Analysis of UNSW-NB15\n\n\t\tAll Features ")

abcall = AdaBoostClassifier(DecisionTreeClassifier(max_depth=3),
                         algorithm="SAMME",
                         n_estimators=500)

abcall.fit(df3_xtrain,df3_ytrain)

y_pred_Adaall = abcall.predict(df3_xtest)

results_Adaall = confusion_matrix(df3_ytest, y_pred_Adaall) 
print ('Confusion Matrix :')
print(results_Adaall)

print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_Adaall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_Adaall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_Adaall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_Adaall, average='macro'))


		AdaBoost using DT Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[  249    47   167    15    19    22    36   122     0     0]
 [  187    89   161    23    24    10     0    89     0     0]
 [  974   503   498   587   129   130   135  1133     0     0]
 [ 1484   826   974  3572   154   818  1291  2012     0     1]
 [  441   623   700  1169  1438   862   235   594     0     0]
 [   12    42    79   355     6 14056    41  4280     0     0]
 [ 2176  1149  1646  4170  6526   947 15579  4807     0     0]
 [   85   128    52    69    21    15     2  3124     0     0]
 [    0    67    74   169     7     0     0    61     0     0]
 [    0     0     5     8     1     0     0    30     0     0]]
Accuracy Score : 0.46889423310498957
Precision Score:  0.26348940439217894
F1 Score:  0.24536069780208208
Recall:  0.32598334581360233


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
!pip install vecstack

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from vecstack import stacking

  Created wheel for vecstack: filename=vecstack-0.4.0-cp37-none-any.whl size=19877 sha256=480b01f35ca08e04019efc21d0b0c8f7a025131639a1df54c8388885d2936bea
  Stored in directory: /root/.cache/pip/wheels/5f/bb/4e/f6488433d53bc0684673d6845e5bf11a25240577c8151c140e
Successfully built vecstack


In [ ]:
models = [
    KNeighborsClassifier(),
        
    RandomForestClassifier(n_estimators=500, max_depth=3),
        
    XGBClassifier(random_state=0, n_jobs=-1, learning_rate=0.1, 
                  n_estimators=100, max_depth=3)
]

In [ ]:
S_train, S_test = stacking(models, df1_xtrain, df1_ytrain, df1_xtest, regression=False, mode='oof_pred_bag', needs_proba=False, save_dir=None,  metric=accuracy_score, 
                               n_folds=5, stratified=True, shuffle=True,  random_state=0, verbose=2)

task:         [classification]
n_classes:    [10]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [KNeighborsClassifier]
    fold  0:  [0.73357156]
    fold  1:  [0.74108966]
    fold  2:  [0.73417487]
    fold  3:  [0.73937256]
    fold  4:  [0.74043995]
    ----
    MEAN:     [0.73772972] + [0.00320190]
    FULL:     [0.73772972]

model  1:     [RandomForestClassifier]
    fold  0:  [0.72196956]
    fold  1:  [0.72874513]
    fold  2:  [0.72688881]
    fold  3:  [0.73575274]
    fold  4:  [0.73166883]
    ----
    MEAN:     [0.72900501] + [0.00461890]
    FULL:     [0.72900501]

model  2:     [XGBClassifier]
    fold  0:  [0.78893633]
    fold  1:  [0.79547986]
    fold  2:  [0.79650084]
    fold  3:  [0.79961017]
    fold  4:  [0.79520141]
    ----
    MEAN:     [0.79514572] + [0.00347675]
    FULL:     [0.79514572]



In [ ]:
model1 = XGBClassifier(random_state=1, n_jobs=-1, learning_rate=0.1, 
                      n_estimators=300, max_depth=3)
    
model1 = model1.fit(S_train, df1_ytrain)

y_pred_XGB1 = model1.predict(S_test)

print('Final prediction score: [%.5f]' % accuracy_score(df1_ytest, y_pred_XGB1))

results_XGB1 = confusion_matrix(df1_ytest, y_pred_XGB1) 
print ('Confusion Matrix :')
print(results_XGB1) 

print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_XGB1) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_XGB1, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_XGB1, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_XGB1, average='macro'))


Final prediction score: [0.73230]
Confusion Matrix :
[[  135     0     0     8   479     0    52     3     0     0]
 [   91    20     1    32   424     0     7     4     4     0]
 [  709    41    67  1027  2090     3    44    44    64     0]
 [  712    21    32  7272  2536     1   306   184    65     3]
 [  268     7     1   143  4550     0   944    54    95     0]
 [    9     4    12   495   154 18159    18     9    10     1]
 [   20     0    19  1076  8743     0 27033    35    73     1]
 [   84     5     2   289   267     0     6  2826    15     2]
 [    2     1     2    55    63     0    10    30   215     0]
 [    0     0     1    22     5     0     1     0     0    15]]
Accuracy Score : 0.7323033571393869
Precision Score:  0.5607490663332098
F1 Score:  0.4798632725863362
Recall:  0.5064865487367871


In [ ]:
S_train2, S_test2 = stacking(models, df2_xtrain, df2_ytrain, df2_xtest, regression=False, mode='oof_pred_bag', needs_proba=False, save_dir=None,  metric=accuracy_score, 
                               n_folds=5, stratified=True, shuffle=True,  random_state=0, verbose=2)

model2 = XGBClassifier(random_state=0, n_jobs=-1, learning_rate=0.1, n_estimators=300, max_depth=3)
    
model2 = model2.fit(S_train2, df2_ytrain)

y_pred_XGB2 = model2.predict(S_test2)

print('Final prediction score: [%.5f]' % accuracy_score(df2_ytest, y_pred_XGB2))




results_XGB2 = confusion_matrix(df2_ytest, y_pred_XGB2) 
print ('Confusion Matrix :')
print(results_XGB2) 
print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_XGB2) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_XGB2, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_XGB2, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_XGB2, average='macro'))



task:         [classification]
n_classes:    [10]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [KNeighborsClassifier]
    fold  0:  [0.56775571]
    fold  1:  [0.56798775]
    fold  2:  [0.56993689]
    fold  3:  [0.56432151]
    fold  4:  [0.57156117]
    ----
    MEAN:     [0.56831260] + [0.00243047]
    FULL:     [0.56831260]

model  1:     [RandomForestClassifier]
    fold  0:  [0.70772229]
    fold  1:  [0.71575088]
    fold  2:  [0.71366252]
    fold  3:  [0.70790793]
    fold  4:  [0.70609801]
    ----
    MEAN:     [0.71022833] + [0.00376872]
    FULL:     [0.71022833]

model  2:     [XGBClassifier]
    fold  0:  [0.79394839]
    fold  1:  [0.80165213]
    fold  2:  [0.79974940]
    fold  3:  [0.80466865]
    fold  4:  [0.80230184]
    ----
    MEAN:     [0.80046408] + [0.00361752]
    FULL:     [0.80046408]

Final prediction score: [0.73306]
Confusion Matrix :
[[   77   215     0     1   320     0    59     2     3     0]
 [   25

In [ ]:

S_train3, S_test3 = stacking(models, df3_xtrain, df3_ytrain, df3_xtest, regression=False, mode='oof_pred_bag', needs_proba=False, save_dir=None,  metric=accuracy_score, 
                               n_folds=5, stratified=True, shuffle=True,  random_state=0, verbose=2)


model3 = XGBClassifier(random_state=0, n_jobs=-1, learning_rate=0.1, n_estimators=300, max_depth=3)
    
model3 = model3.fit(S_train3, df3_ytrain)

y_pred_XGB3 = model3.predict(S_test)

print('Final prediction score: [%.5f]' % accuracy_score(df3_ytest, y_pred_XGB3))




results_XGB3 = confusion_matrix(df3_ytest, y_pred_XGB3) 
print ('Confusion Matrix :')
print(results_XGB3) 
print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_XGB3) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_XGB3, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_XGB3, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_XGB3, average='macro'))


task:         [classification]
n_classes:    [10]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [KNeighborsClassifier]
    fold  0:  [0.56682755]
    fold  1:  [0.56585298]
    fold  2:  [0.56835901]
    fold  3:  [0.56283646]
    fold  4:  [0.57040097]
    ----
    MEAN:     [0.56685539] + [0.00252940]
    FULL:     [0.56685539]

model  1:     [RandomForestClassifier]
    fold  0:  [0.69570262]
    fold  1:  [0.70572675]
    fold  2:  [0.70359198]
    fold  3:  [0.70707258]
    fold  4:  [0.70489141]
    ----
    MEAN:     [0.70339707] + [0.00401030]
    FULL:     [0.70339707]

model  2:     [XGBClassifier]
    fold  0:  [0.79227771]
    fold  1:  [0.79956376]
    fold  2:  [0.79942454]
    fold  3:  [0.80517913]
    fold  4:  [0.79933172]
    ----
    MEAN:     [0.79915537] + [0.00409532]
    FULL:     [0.79915537]



XGBoostError: ignored

In [ ]:
from sklearn.datasets import make_classification
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [ ]:
level0 = list()
level0.append(('rf', RandomForestClassifier()))
#level0.append(('knn', KNeighborsClassifier()))
level0.append(('cart', DecisionTreeClassifier()))
# define meta learner model
print("Proceeding with: ",level0)
level1 = GradientBoostingClassifier(n_estimators=200)
# define the stacking ensemble
model = StackingClassifier(estimators=level0, final_estimator=level1, cv=2)
# fit the model on all available data
model.fit(df1_xtrain, df1_ytrain)
# make a prediction for one example

yhat = model.predict(df1_xtest)
#print('Predicted Class: %d' % (yhat))

print('Final prediction score: [%.5f]' % accuracy_score(df1_ytest, yhat))

results_sc1 = confusion_matrix(df1_ytest, yhat) 
print ('Confusion Matrix :')
print(results_sc1) 

print ('Accuracy Score :',accuracy_score(df1_ytest, yhat) )
print("Precision Score: ",precision_score(df1_ytest, yhat, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, yhat, average='macro'))
print("Recall: ",recall_score(df1_ytest, yhat, average='macro'))

Final prediction score: [0.67519]
Confusion Matrix :
[[   67   183    39   176   194     7     3     5     3     0]
 [   23   207    38   119   167     7     6     4    12     0]
 [  520   527   793  1071   882    31    74   137    54     0]
 [  504   655   491  7815  1055    37   101   352   122     0]
 [   87   363   119   654  4138    17   331    21   332     0]
 [   12    16    41   427   178 18005   140     3    48     1]
 [ 1449     4    51   854 12999     6 21445     5   186     1]
 [   64    51    68   304   116     1    12  2829    51     0]
 [    1     1    14    38    29     2     2     1   290     0]
 [    0     1     0    38     2     1     0     0     1     1]]
Accuracy Score : 0.6751931205363649
Precision Score:  0.489997169317403
F1 Score:  0.44466007373387406
Recall:  0.5165441831566977
