In [ ]:
import numpy as np 
import matplotlib
import matplotlib.pyplot as plt
import os
import math
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_validate
from sklearn import datasets, preprocessing, feature_extraction, neighbors
from sklearn import linear_model, svm, metrics, ensemble, tree, ensemble
from sklearn.model_selection import train_test_split
from copy import copy
import urllib
import csv

import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import plotly.graph_objs as go

from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 


from sklearn.naive_bayes import GaussianNB
from yellowbrick.classifier import ClassificationReport

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC # "Support Vector Classifier" 
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from zipfile import ZipFile
import collections

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
import pickle

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning:

The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.



In [ ]:
!git clone https://github.com/ishaak15/UNSW-IDS-Feature-Selection.git

fatal: destination path 'UNSW-IDS-Feature-Selection' already exists and is not an empty directory.


In [ ]:
cd UNSW-IDS-Feature-Selection/

/content/UNSW-IDS-Feature-Selection


In [ ]:
ls

clfDT_10.sav    Dataset1.csv  README.md     UNSW-IDS-Feature-Selection/
clfKNN10.sav    Dataset2.csv  Testset1.csv  UNSW_NB15_testing-set.csv
clfKNN20.sav    Dataset3.csv  Testset2.csv
clfKNN_all.sav  LICENSE       Testset3.csv


In [ ]:
df1 = pd.read_csv('Dataset1.csv',index_col=0)
df2 = pd.read_csv('Dataset2.csv',index_col=0)
df3 = pd.read_csv('Dataset3.csv',index_col=0)

In [ ]:
tf1 = pd.read_csv('Testset1.csv',index_col=0)
tf2 = pd.read_csv('Testset2.csv',index_col=0)
tf3 = pd.read_csv('Testset3.csv',index_col=0)

In [ ]:
df1_xtrain=df1.iloc[: , :-1]
df1_ytrain=df1.iloc[:,-1]
df2_xtrain=df2.iloc[: , :-1]
df2_ytrain=df2.iloc[:,-1]
df3_xtrain=df3.iloc[: , :-1]
df3_ytrain=df3.iloc[:,-1]

In [ ]:
df1_xtest=tf1.iloc[: , :-1]
df1_ytest=tf1.iloc[:,-1]
df2_xtest=tf2.iloc[: , :-1]
df2_ytest=tf2.iloc[:,-1]
df3_xtest=tf3.iloc[: , :-1]
df3_ytest=tf3.iloc[:,-1]

In [ ]:
#KNN

In [ ]:
clfKNN10=neighbors.KNeighborsClassifier()
clfKNN10.fit(df1_xtrain,df1_ytrain)

pickle.dump(clfKNN10, open("clfKNN10.sav", 'wb'))   #save model

print ("\t\tKNN Classification of UNSW-NB15\n\n\t\tTop 10 Features ")

yt_pred_10 = clfKNN10.predict(df1_xtest)
results = confusion_matrix(df1_ytest, yt_pred_10) 
print ('Confusion Matrix :')
print(results) 


accKNN10=accuracy_score(df1_ytest,yt_pred_10)
print("Accuracy: ",accKNN10)
preKNN10=precision_score(df1_ytest, yt_pred_10, average='macro')
print("Precision Score: ",preKNN10)
f1KNN10=f1_score(df1_ytest, yt_pred_10, average='macro')
print("F1 Score: ",f1KNN10)
reKNN10=recall_score(df1_ytest, yt_pred_10, average='macro')  
print("Recall: ",reKNN10)


		KNN Classification of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[  208   131    42    58   129    16    32    61     0     0]
 [  198   121    13    49   134    18    16    33     1     0]
 [  822   758   472   913   502    21   202   372    27     0]
 [  955   835   503  6664   944    39   616   540    33     3]
 [  444   315    97   469  3357    54  1111   164    50     1]
 [   17    11    34   375   168 18078   140    44     4     0]
 [  496    52   218  1986  7076    20 26822   233    93     4]
 [   82   102    51   324   117     5    71  2737     5     2]
 [    5     7    12    50   161     6    51    32    54     0]
 [    0     1     2    26    11     0     3     0     0     1]]
Accuracy:  0.7107078657144246
Precision Score:  0.41756373950870634
F1 Score:  0.4023931552335053
Recall:  0.44140047486900985


In [ ]:
clfKNN20=neighbors.KNeighborsClassifier()
clfKNN20.fit(df2_xtrain,df2_ytrain)

pickle.dump(clfKNN20, open("clfKNN20.sav", 'wb'))   #save model

print ("\t\tKNN Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

y_pred_20 = clfKNN20.predict(df2_xtest)
results = confusion_matrix(df2_ytest, y_pred_20) 
print ('Confusion Matrix :')
print(results) 


accKNN20=accuracy_score(df2_ytest,y_pred_20)
print("Accuracy: ",accKNN20)
preKNN20=precision_score(df2_ytest, y_pred_20, average='macro')
print("Precision Score: ",preKNN20)
f1KNN20=f1_score(df2_ytest, y_pred_20, average='macro')
print("F1 Score: ",f1KNN20)
reKNN20=recall_score(df2_ytest, y_pred_20, average='macro')  
print("Recall: ",reKNN20)


		KNN Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  267   167    15    69   117    16    17     9     0     0]
 [  251   109     6    65   118    18    11     5     0     0]
 [ 1150  1136   184   646   494    22   307   129    21     0]
 [ 1321  1139   396  4316  1854    39  1749   290    28     0]
 [  599   332   140  2053  1702    56  1023   122    35     0]
 [   30    22    26   304   220 18083   132    51     3     0]
 [  132    71   537  7955  4981    21 22760   473    69     1]
 [  126   152    91   985   400     7   405  1325     5     0]
 [    7     6    13   109   126     5    52    17    43     0]
 [    0     0     1    22     8     0    13     0     0     0]]
Accuracy:  0.5925885439440315
Precision Score:  0.3273066113090913
F1 Score:  0.3053129978339978
Recall:  0.336096541715301


In [ ]:
clfKNN_all=neighbors.KNeighborsClassifier()
clfKNN_all.fit(df3_xtrain,df3_ytrain)

pickle.dump(clfKNN_all, open("clfKNN_all.sav", 'wb'))   #save model

print ("\t\tKNN Analysis of UNSW-NB15\n\n\t\tAll Features ")

y_pred_all = clfKNN_all.predict(df3_xtest)
results = confusion_matrix(df3_ytest, y_pred_all) 
print ('Confusion Matrix :')
print(results) 


accKNNall=accuracy_score(df3_ytest, y_pred_all)
print("Accuracy: ",accKNNall)
preKNNall=precision_score(df3_ytest, y_pred_all, average='macro')
print("Precision Score: ",preKNNall)
f1KNNall=f1_score(df3_ytest, y_pred_all, average='macro')
print("F1 Score: ",f1KNNall)
reKNNall=recall_score(df3_ytest, y_pred_all, average='macro')  
print("Recall: ",reKNNall)


		KNN Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[  336   161     1    44   101    16    17     1     0     0]
 [  304    98     1    44   105    18    11     2     0     0]
 [ 1491  1070   101   581   437    22   305    61    21     0]
 [ 1671  1073   319  4245  1794    39  1743   220    28     0]
 [  726   307   123  2007  1672    56  1024   112    35     0]
 [   37    21    26   301   219 18083   130    51     3     0]
 [  115    55   537  7955  5009    21 22765   473    69     1]
 [  164   146    81   981   392     7   405  1315     5     0]
 [    6     3    13   109   132     5    50    16    44     0]
 [    0     0     1    22     8     0    13     0     0     0]]
Accuracy:  0.5910095710051985
Precision Score:  0.3265665197965294
F1 Score:  0.3034833731074776
Recall:  0.34123127222810123


In [ ]:
#Decision TREE

In [ ]:
clfDT_10 = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

# Train Decision Tree Classifer
clfDT_10 = clfDT_10.fit(df1_xtrain,df1_ytrain)

#Predict the response for test dataset
y_pred_DT10 = clfDT_10.predict(df1_xtest)

pickle.dump(clfDT_10, open("clfDT_10.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation")
results_DT10 = confusion_matrix(df1_ytest, y_pred_DT10) 
print ('Confusion Matrix :')
print(results_DT10) 


print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_DT10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_DT10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_DT10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_DT10, average='macro'))



		Decision Tree Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[  378    82     3     3   190     0    21     0     0     0]
 [  317    57     3     8   188     1     5     0     4     0]
 [ 1484  1028   522   522   379    34    58    24    36     2]
 [ 1702   929   614  6522   629   125   234   227   136    14]
 [  720   142   152   533  2864    39  1309     5   293     5]
 [   19    25    70   236    43 18432    20     4    17     5]
 [  606    10  1103  1172  7284    74 26588    20   142     1]
 [  159   147    33   267    42     4    37  2767    38     2]
 [    1     6    14    40    27     5    14     5   266     0]
 [    0     1     0    15     0     1     1     0     1    25]]
Accuracy Score : 0.7095782927658747
Precision Score:  0.4826660833630867
F1 Score:  0.4838423933263322
Recall:  0.5600798136827534


In [ ]:
clfDT_20 = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

# Train Decision Tree Classifer
clfDT_20 = clfDT_20.fit(df2_xtrain,df2_ytrain)

#Predict the response for test dataset
y_pred_DT20 = clfDT_20.predict(df2_xtest)

pickle.dump(clfDT_20, open("clfDT_20.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation")
results_DT20 = confusion_matrix(df2_ytest, y_pred_DT20) 
print ('Confusion Matrix :')
print(results_DT20)

print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_DT20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_DT20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_DT20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_DT20, average='macro'))

		Decision Tree Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[  505   116     0    34     1     2    16     0     3     0]
 [  491    50     4    11    10     0    13     0     4     0]
 [ 1747  1023   557   502   102    32    64    26    36     0]
 [ 2101   961   720  6441   176    78   297   251    98     9]
 [ 1067   154    97   397  2673    23  1481    18   152     0]
 [   26    27    56   208    34 18479    15     6    15     5]
 [  679    11  1267  1481  7371    74 25905    57   154     1]
 [  169   145    36   281    34     2    34  2749    45     1]
 [    1     8    16    50    31     1    14     4   253     0]
 [    0     1     1    16     0     1     0     1     1    23]]
Accuracy Score : 0.7000315794587767
Precision Score:  0.4961306956436092
F1 Score:  0.48949320146818937
Recall:  0.564519538440563


In [ ]:
clfDT_all = DecisionTreeClassifier()
print ("\t\tDecision Tree Analysis of UNSW-NB15\n\n\t\tAll Features ")

# Train Decision Tree Classifer
clfDT_all = clfDT_all.fit(df3_xtrain,df3_ytrain)

#Predict the response for test dataset
y_pred_DTall = clfDT_all.predict(df3_xtest)

pickle.dump(clfDT_all, open("clfDT_all.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation")
results_DTall = confusion_matrix(df3_ytest, y_pred_DTall) 
print ('Confusion Matrix :')
print(results_DTall)

print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_DTall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_DTall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_DTall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_DTall, average='macro'))

		Decision Tree Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[  503   113     0    53     1     1     5     0     1     0]
 [  494    61     1    10     5     0     8     0     4     0]
 [ 1727  1108   533   501    60    39    58    26    37     0]
 [ 2101  1026   550  6484   154    91   397   228    91    10]
 [ 1059   175    79   368  2707    24  1489     6   155     0]
 [   25    25    67   254    34 18428    18     1    14     5]
 [  697    10  1059  1455  7498   241 25866    43   130     1]
 [  166   154    36   295    14     3    38  2746    43     1]
 [    0     8    12    48    35     3    14     4   254     0]
 [    0     2     4    14     1     1     0     1     0    21]]
Accuracy Score : 0.6996429091969101
Precision Score:  0.49719488121178557
F1 Score:  0.48781938695364396
Recall:  0.5617287361595836


In [ ]:
#Gaussian Naive Bayes Classifier


In [ ]:
bayes_10 = GaussianNB()
bayes_10.fit(df1_xtrain,df1_ytrain)

print ("\t\tGaussain Naive Bayes Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")
y_pred_gnb10 = bayes_10.predict(df1_xtest)

pickle.dump(bayes_10, open("bayes_10.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df1_ytest, y_pred_gnb10) 
print ('Confusion Matrix :')
print(results) 

print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_gnb10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_gnb10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_gnb10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_gnb10, average='macro'))


		Gaussain Naive Bayes Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[   75     0     0     0     0     0     0   573    29     0]
 [   48     0     0     0     5     0     1   509    20     0]
 [  497     0     7    70   145     0   133  3108   129     0]
 [  464     0    32   291   830     0  1686  7679   150     0]
 [  207     0     0    46   677     0     8  4877   247     0]
 [ 3241     0     1    13    94     0   158 15342    22     0]
 [  537     0     0   478  1726     5 14926 18681   647     0]
 [  215     0     0     2    14    46     6  3202    11     0]
 [   10     0     0     0    11     0     0   311    46     0]
 [    0     0     0     0     2     0     7    33     2     0]]
Accuracy Score : 0.2334936598163533
Precision Score:  0.16818543254569654
F1 Score:  0.09375138218594578
Recall:  0.16913173617946867


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
bayes_20 = GaussianNB()
bayes_20.fit(df2_xtrain,df2_ytrain)

print ("\t\tGaussian Naive Bayes Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

y_pred_gnb20 = bayes_20.predict(df2_xtest)

pickle.dump(bayes_20, open("bayes_20.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df2_ytest, y_pred_gnb20) 
print ('Confusion Matrix :')
print(results)

print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_gnb20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_gnb20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_gnb20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_gnb20, average='macro'))

		Gaussian Naive Bayes Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[    0   606     0     0     4    13     0    54     0     0]
 [    0   520     0     0     1    10     1    51     0     0]
 [    0  2907    20    74    73    58    83   874     0     0]
 [    0  3177    64   423   452    57  1157  5799     0     3]
 [    0  1831     0    36   897    49     1  3248     0     0]
 [    0 17695     7    26    97   553   118   373     0     2]
 [    0  4851   137   359  2121   264 12607 16642     1    18]
 [    0  1575     0     4     9    51     3  1854     0     0]
 [    0   159     0     0    20     5     0   192     2     0]
 [    0     4     0     0     2     0     6    31     0     1]]
Accuracy Score : 0.20498712529757568
Precision Score:  0.30018734498583144
F1 Score:  0.09980681588758283
Recall:  0.20111715485364745


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
bayes_all = GaussianNB()
bayes_all.fit(df3_xtrain,df3_ytrain)

print ("\t\tGaussian Naive Bayes Analysis of UNSW-NB15\n\n\t\tAll Features ")
y_pred_gnball = bayes_all.predict(df3_xtest)

pickle.dump(bayes_all, open("bayes_all.sav", 'wb'))   #save model

#print ("\t\tMajor Verifcation KDD99 10% GNB")
results = confusion_matrix(df3_ytest, y_pred_gnball) 
print ('Confusion Matrix :')
print(results)

print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_gnball) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_gnball, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_gnball, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_gnball, average='macro'))

		Gaussian Naive Bayes Analysis of UNSW-NB15

		All Features 
Confusion Matrix :
[[    0   606     0     0     4    13     0    54     0     0]
 [    0   520     0     0     1    10     1    51     0     0]
 [    0  2907    22    63    75    51    84   884     0     3]
 [    0  3177    62   223   478    55  1273  5852     0    12]
 [    0  1853     0    28   905    27     1  3248     0     0]
 [    0 17695     8    12    98   553   128   376     0     1]
 [    0  5065   149    75  2137    15 12817 16712     5    25]
 [    0  1575     0     2     9    51     5  1854     0     0]
 [    0   159     0     0    20     4     0   192     3     0]
 [    0     4     1     0     2     0     5    31     0     1]]
Accuracy Score : 0.20524219015692563
Precision Score:  0.29699325663164
F1 Score:  0.09720051271184418
Recall:  0.20033353169712004


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
#Random Forest Classifier 


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

#Create a Gaussian Classifier
clfRF_10=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_10.fit(df1_xtrain,df1_ytrain)

y_pred_RF10=clfRF_10.predict(df1_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

pickle.dump(clfRF_10, open("clfRF_10.sav", 'wb'))   #save model

results_10 = confusion_matrix(df1_ytest, y_pred_RF10) 
print ('Confusion Matrix :')
print(results_10) 
print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_RF10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_RF10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_RF10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_RF10, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 10 Features 
Confusion Matrix :
[[   32   113    19    50   407     0    36    17     3     0]
 [   25    68    13    17   412     3    24    14     7     0]
 [  388  1293   555   795   811    15    39   146    46     1]
 [  382  1204   245  7530  1244    19   147   277    79     5]
 [   86   209    36   422  3965     8  1069    34   233     0]
 [    5     8    41   415    60 18312     9     1    18     2]
 [  317     0    56   712  7419     5 28356    11   123     1]
 [   48   166    32   329    86     0    17  2789    29     0]
 [    0     1    11    50    34     0     9     2   270     1]
 [    0     0     0    19     1     2     1     0     0    21]]
Accuracy Score : 0.7518097459068163
Precision Score:  0.5411389698559282
F1 Score:  0.504689487509652
Recall:  0.5356221846909366


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 20 Features ")

#Create a Gaussian Classifier
clfRF_20=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_20.fit(df2_xtrain,df2_ytrain)

y_pred_RF20=clfRF_20.predict(df2_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

pickle.dump(clfRF_20, open("clfRF_20.sav", 'wb'))   #save model

results_20 = confusion_matrix(df2_ytest, y_pred_RF20) 
print ('Confusion Matrix :')
print(results_20) 
print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_RF20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_RF20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_RF20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_RF20, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 20 Features 
Confusion Matrix :
[[   43   218     4    52   267     0    15    75     3     0]
 [   37   147     8    21   283     0     7    74     6     0]
 [  499  1460   452   827   591     7    29   183    40     1]
 [  498  1417   121  7620   926    13    97   364    72     4]
 [  123   377    16   353  3949     2   874   150   218     0]
 [    4     9    42   376    62 18337     9    11    18     3]
 [  417     1    31   746  7766     6 27896     6   131     0]
 [   60   177    20   316    73     0     6  2821    23     0]
 [    0     1    11    52    43     0     8     2   260     1]
 [    0     0     0    28     2     1     2     0     0    11]]
Accuracy Score : 0.7474129135694505
Precision Score:  0.5336292995539532
F1 Score:  0.48073545877717044
Recall:  0.5232549794678787


In [ ]:
print ("\t\tRandom Forest Analysis of UNSW-NB15\n\n\t\tTop 30 Features ")

#Create a Random Forest Classifier
clfRF_all=RandomForestClassifier()

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF_all.fit(df3_xtrain,df3_ytrain)

y_pred_RFall=clfRF_all.predict(df3_xtest)
#print("Accuracy Random Forest:",metrics.accuracy_score(y_test, y_pred_RF))

pickle.dump(clfRF_all, open("clfRF_all.sav", 'wb'))   #save model

results_all = confusion_matrix(df3_ytest, y_pred_RFall) 
print ('Confusion Matrix :')
print(results_all) 
print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_RFall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_RFall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_RFall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_RFall, average='macro'))

		Random Forest Analysis of UNSW-NB15

		Top 30 Features 
Confusion Matrix :
[[   64   207    12    69   251     0     4    67     3     0]
 [   64   122    15    31   274     0     1    70     6     0]
 [  308  1694   471   782   583     5    30   168    48     0]
 [  365  1635   134  7597   873    11    85   361    70     1]
 [  150   357    34   381  3915     3   868   141   213     0]
 [    1     7    41   409    61 18318     6     5    21     2]
 [  457     0    27   741  7676     5 27962     7   125     0]
 [   34   211    18   314    72     1     7  2816    23     0]
 [    0     0     9    62    44     0     5     2   255     1]
 [    0     0     0    32     3     1     1     0     0     7]]
Accuracy Score : 0.7473036000583005
Precision Score:  0.5414219325543516
F1 Score:  0.47283750146953335
Recall:  0.5112869275363296


In [ ]:
#Logistic Regression Classifier 


In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW-NB15\n\n\t\tTop 10 Features ")

logisticRegr_10 = LogisticRegression(C=1e5, solver='newton-cg',max_iter=1000, multi_class='multinomial')

logisticRegr_10.fit(df1_xtrain,df1_ytrain)

y_pred_LR10 = logisticRegr_10.predict(df1_xtest)

results_LR10 = confusion_matrix(df1_ytest, y_pred_LR10) 
print ('Confusion Matrix :')
print(results_LR10) 
print ('Accuracy Score :',accuracy_score(df1_ytest, y_pred_LR10) )
print("Precision Score: ",precision_score(df1_ytest, y_pred_LR10, average='macro'))
print("F1 Score: ",f1_score(df1_ytest, y_pred_LR10, average='macro'))
print("Recall: ",recall_score(df1_ytest, y_pred_LR10, average='macro'))

		Logistic Regression Analysis of UNSW-NB15

		Top 10 Features 


/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:466: LineSearchWarning:

The line search algorithm did not converge

/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:314: LineSearchWarning:

The line search algorithm did not converge



In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW NB15\n\n\t\tTop 20 Features ")

logisticRegr_20 = LogisticRegression(C=1e5, solver='newton-cg',max_iter=1000, multi_class='multinomial')

logisticRegr_20.fit(df2_xtrain,df2_ytrain)

y_pred_LR20 = logisticRegr_20.predict(df2_xtest)

results_LR20 = confusion_matrix(df2_ytest, y_pred_LR20) 
print ('Confusion Matrix :')
print(results_LR20) 
print ('Accuracy Score :',accuracy_score(df2_ytest, y_pred_LR20) )
print("Precision Score: ",precision_score(df2_ytest, y_pred_LR20, average='macro'))
print("F1 Score: ",f1_score(df2_ytest, y_pred_LR20, average='macro'))
print("Recall: ",recall_score(df2_ytest, y_pred_LR20, average='macro'))


In [ ]:
print ("\t\tLogistic Regression Analysis of UNSW-NB15\n\n\t\tTop 30 Features ")

logisticRegr_all = LogisticRegression(C=1e5, solver='Newton-cg', multi_class='multinomial')

logisticRegr_all.fit(df3_xtrain,df3_ytrain)

y_pred_LRall = logisticRegr_all.predict(df3_xtest)

results_LRall = confusion_matrix(df3_ytest, y_pred_LRall) 
print ('Confusion Matrix :')
print(results_LRall) 
print ('Accuracy Score :',accuracy_score(df3_ytest, y_pred_LRall) )
print("Precision Score: ",precision_score(df3_ytest, y_pred_LRall, average='macro'))
print("F1 Score: ",f1_score(df3_ytest, y_pred_LRall, average='macro'))
print("Recall: ",recall_score(df3_ytest, y_pred_LRall, average='macro'))



In [ ]:
#CNN 1D
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.layers import Conv1D,GlobalAveragePooling1D,MaxPooling1D
import numpy as np
import pandas as pd
from sklearn.preprocessing import Normalizer

In [ ]:
scaler=Normalizer().fit(df1)
x_train=scaler.transform(train)
scaler=Normalizer().fit(test)
x_test=scaler.transform(test)
x=np.expand_dims(x_train,axis=2)
y=np.expand_dims(x_test,axis=2)

tr_lb=np.reshape(train_lb,494021)
te_lb=np.reshape(test_lb,20000)

cnn_1D=Sequential()
cnn_1D.add(Conv1D(64,1,activation='relu',input_shape=(8,1)))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(MaxPooling1D(3))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(GlobalAveragePooling1D())
cnn_1D.add(Dropout(0.5))
cnn_1D.add(Dense(6,activation='sigmoid'))
cnn_1D.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='rmsprop',
    metrics=(['accuracy'])
)
cnn_1D.fit(x,tr_lb,batch_size=80,epochs=30)
score=cnn_1D.evaluate(y,te_lb,batch_size=80)
print(score)